app/Http/routes.php
<?php  

use Illuminate\Support\Facades\Redis;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/clear-cache', function() {

    $exitCode = Artisan::call('config:cache');

    return back();

})->name('clear-cache');


// Generral configuration routes 

Route::post('project/configurations' , 'ApplicationController@configuration_site');

// UI

Route::get('/video_notification' , 'SampleController@video_notification');

Route::get('/upload_videoUI' , 'SampleController@upload_video');

// Unused Sample Routes

Route::post('angelo/in-app-purchase' , 'SampleController@angelo_in_app_purchase');

Route::get('/addIndex', 'ApplicationController@addIndex')->name('addIndex');

Route::get('/addAll', 'ApplicationController@addAllVideoToEs')->name('addAll');

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');


// Chat Message save


Route::get('message/save' , 'ApplicationController@message_save')->name('message.save');


// Cron jobs

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal')->name('automatic.renewal');

// Application Routes

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

// Installation

Route::get('/install/configure', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/install/theme', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');

Route::get('/user_session_language/{lang}', 'ApplicationController@set_session_language')->name('user_session_language');

Route::get('admin-control', 'ApplicationController@admin_control')->name('control');

Route::post('admin-control', 'ApplicationController@save_admin_control')->name('admin.save.control');

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');


// Social Login

Route::post('/social', array('as' => 'SocialLogin' , 'uses' => 'SocialAuthController@redirect'));

Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    

// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');


Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');


Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function(){

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    // Admin Dashboard 
    
    Route::get('/', 'AdminController@dashboard')->name('dashboard');


    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // User CRUD Operations

    Route::get('/users/list', 'AdminController@users_list')->name('users');

    Route::get('/users/create', 'AdminController@users_create')->name('users.create');
    Route::get('/users/password/{id}', 'AdminController@user_password')->name('users.password');
    

    Route::get('/users/edit', 'AdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'AdminController@users_save')->name('users.save');
    Route::post('/users/password', 'AdminController@users_password')->name('users.password');
    

    Route::get('/users/view/{id}', 'AdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'AdminController@users_delete')->name('users.delete');

    Route::get('/users/status','AdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/{id?}', 'AdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/{id}', 'AdminController@users_channels')->name('users.channels');

    Route::get('/users/history/{id}', 'AdminController@users_history')->name('users.history');
    Route::get('users/type/{id}','AdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/{id}', 'AdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/{id}', 'AdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/{id}', 'AdminController@users_wishlist_delete')->name('users.wishlist.delete');

    //User Subscriptions

    Route::get('/users/subscriptions/{id}', 'AdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save/{s_id}/u_id/{u_id}', 'AdminController@users_subscription_paln_save')->name('users.subscription.save');

    // Referrals

    Route::get('/users/referrals', 'AdminController@users_referrals')->name('users.referrals');

    Route::get('/users/referrals/view', 'AdminController@users_referrals_view')->name('users.referrals.view');


    // Channel CRUD Operations

    Route::get('/channels', 'AdminController@channels')->name('channels');

    Route::get('/channels/create', 'AdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit/{id}', 'AdminController@channels_edit')->name('channels.edit');

    Route::get('/channels/videos/{id?}', 'AdminController@channels_videos')->name('channels.videos');

    Route::post('/channels/save', 'AdminController@channels_save')->name('channels.save');

    Route::get('/channels/delete', 'AdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view/{id}', 'AdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'AdminController@channels_status_change')->name('channel.approve');

    Route::get('/channels/subscribers', 'AdminController@channels_subscribers')->name('channels.subscribers');


    // Videos CRUD Operations

    Route::get('/videos/create', 'AdminController@videos_create')->name('videos.create');

    Route::get('/videos/edit/{id}', 'AdminController@videos_edit')->name('videos.edit');

    Route::post('/videos/save', 'AdminController@videos_save')->name('videos.save');

    Route::get('/videos/images/{id}', 'AdminController@videos_images')->name('videos.images');

    Route::post('/videos/upload/image', 'AdminController@videos_upload_image')->name('videos.upload_image');

    Route::post('videos/save/default_img', 'AdminController@videos_save_default_img')->name('videos.save.default_img');

    Route::get('/videos/list/{id?}', 'AdminController@videos_list')->name('videos.list');

    Route::get('/videos/view', 'AdminController@videos_view')->name('videos.view');

    Route::post('/videos/set-ppv/{id}', 'AdminController@videos_set_ppv')->name('videos.set-ppv');

    Route::get('/videos/delete/{id}', 'AdminController@videos_delete')->name('videos.delete');

    Route::get('/videos/status/{id}', 'AdminController@videos_status')->name('videos.status');

    Route::get('/videos/publish/{id}', 'AdminController@videos_publish')->name('videos.publish');

    Route::get('/videos/remove-ppv/{id}', 'AdminController@videos_remove_ppv')->name('videos.remove-ppv');

    Route::get('/videos/wishlist/{id}', 'AdminController@videos_wishlist')->name('videos.wishlist');

    // Video compression status

    Route::get('/videos/compression/complete','AdminController@videos_compression_complete')->name('compress.status');


    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

app/Referral.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Referral extends Model
{
    public function userDetails() {

        return $this->belongsTo('App\User', 'user_id');
    }
}

resources/views/admin/users/referrals/index.blade.php
@extends('layouts.admin')

@section('title', tr('referrals'))

@section('content-header') 

{{tr('referrals')}} - 

<a href="{{route('admin.users.view', ['id' => $user_details->id])}}">{{$user_details->name}}</a>

@endsection

@section('breadcrumb')

    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>

    <li><a href="{{route('admin.users')}}"><i class="fa fa-user"></i>{{tr('users')}}</a></li>

    <li><a href="{{route('admin.users.view', ['id' => $user_details->id])}}"><i class="fa fa-user"></i>{{tr('view_user')}}</a></li>

    <li class="active"><i class="fa fa-user"></i> {{tr('referrals')}}</li>

@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        
        <div class="col-xs-12">
          
          	<div class="box box-primary">
	          	
	          	<div class="box-header label-primary">

	                <b style="font-size:18px;">{{tr('referrals')}}</b>

	                <a href="{{route('admin.users.view', $user_details->id)}}" class="btn btn-default pull-right">
	                	{{tr('view_user')}}
	                </a>
	            
	            </div>
	            
	            <div class="box-body table-responsive">

	            	<div class="row col-md-12" style="margin-bottom: 20px">

		            	<ul class="products-list product-list-in-box">

						    <li class="item  col-xs-4">
						        
						        <div class="product-info" style="margin-left: 0">
						            <a href="javascript:void(0)" class="product-title"> 
						            	{{tr('referral_code')}}
						            	
						            </a>
						            <span class="product-description">
						                <b>{{$user_referrer_details->referral_code}}</b>
						            </span>
						        </div>
						    </li>

						    <li class="item col-xs-4" style="margin-left: 10px">
						        
						        <div class="product-info" style="margin-left: 0">
						            <a href="javascript:void(0)" class="product-title">

						            	{{tr('total_referrals')}}

						            </a>
						            <span class="product-description">
						                <span class="badge bg-maroon bg-flat"> 
						                	{{$user_referrer_details->total_referrals}}
						                </span>
						            </span>
						        </div>
						    </li>

						    <li class="item col-xs-3" style="margin-left: 10px">
						        
						        <div class="product-info" style="margin-left: 0">
						            <a href="javascript:void(0)" class="product-title">

						            	{{tr('total_referrals_earnings')}}

						            </a>
						            <span class="product-description">
						                <span class="badge bg-navy bg-flat"> 
						                	{{Setting::get('currency')}} {{$user_referrer_details->total_referrals_earnings}}
						                </span>
						            </span>
						        </div>
						    </li>
	    
						</ul>

					</div>


	            	@if(count($referrals) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>
						    <tr>
						      	<th>{{tr('id')}}</th>
						      	<th>{{tr('username')}}</th>
						      	<th>{{tr('image')}}</th>
						      	<th>{{tr('referral_code')}}</th>
						      	<th>{{tr('created_at')}}</th>
						      	<th>{{tr('action')}}</th>
						    </tr>
						</thead>

						<tbody>

							@foreach($referrals as $i => $referral_details)

							    <tr>
							      	<td>{{$i+1}}</td>

							      	<td>
							      		<a href="{{route('admin.users.view' , $referral_details->id)}}"> 

							      			{{$referral_details->username}}

							      		</a>
							      	</td>

							      	<td >
										<img src="{{$referral_details->picture?: asset('placeholder.png')}}" class="img img-circle" style="width: 50px;height: 50px">
									</td>

									<td >
										{{$referral_details->referral_code}}
									</td>
									<td>{{$referral_details->created_at}}</td>
									<td>
										<a href="{{route('admin.users.referrals.view', ['user_id' => $referral_details->user_id, 'parent_user_id' => $referral_details->parent_user_id])}}" class="btn btn-info">
											More 
											<i class="fa fa-angle-right"></i><i class="fa fa-angle-right"></i>
										</a>
									</td>

							     
							    </tr>
							@endforeach
						
						</tbody>

					</table>
				@else
					<h3 class="no-result">{{tr('no_result_found')}}</h3>
				@endif

	            </div>

          	</div>
        </div>
    </div>

@endsection

resources/views/admin/users/referrals/view.blade.php
@extends('layouts.admin')

@section('title', tr('referrals'))

@section('content-header') 

{{tr('referrals')}} - 

<a href="{{route('admin.users.view', ['id' => $user_details->id])}}">{{$user_details->name}}</a>

@endsection

@section('breadcrumb')

    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>

    <li><a href="{{route('admin.users')}}"><i class="fa fa-user"></i>{{tr('users')}}</a></li>

    <li><a href="{{route('admin.users.view', ['id' => $user_details->id])}}"><i class="fa fa-user"></i>{{tr('view_user')}}</a></li>

    <li class="active"><i class="fa fa-user"></i> {{tr('referrals')}}</li>

@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        
        <div class="col-xs-12">
          
          	<div class="box box-primary">
	          	
	          	<div class="box-header label-primary">

	                <b style="font-size:18px;">{{tr('referrals')}}</b>

	                <a href="{{route('admin.users.view', $user_details->id)}}" class="btn btn-default pull-right">
	                	{{tr('view_user')}}
	                </a>
	            
	            </div>
	            
	            <div class="box-body table-responsive">

	            	<div class="row col-md-12" style="margin-bottom: 20px">

		            	<ul class="products-list product-list-in-box">

						    <li class="item col-xs-3" style="border-bottom: 0px">
						        
						        <div class="product-info" style="margin-left: 0;border-bottom: 0px">
						            <a href="javascript:void(0)" class="product-title"> 
						            	{{tr('referral_code')}}
						            	
						            </a>
						            <span class="product-description">
						                <b>{{$user_referrer_details->referral_code}}</b>
						            </span>
						        </div>
						    </li>

						    <li class="item col-xs-3" style="border-bottom: 0px">
						        
						        <div class="product-info" style="margin-left: 0;">
						            <a href="javascript:void(0)" class="product-title">

						            	{{tr('username')}}

						            </a>
						            <span class="product-description">
						                <span class="badge bg-maroon bg-flat"> 
						                	{{$user_details->name}}
						                </span>
						            </span>
						        </div>
						    </li>

						    <li class="item col-xs-3" style="border-bottom: 0px">
						        
						        <div class="product-info" style="margin-left: 0;border-bottom: 0px">
						            <a href="javascript:void(0)" class="product-title">

						            	{{tr('total_referrals')}}

						            </a>
						            <span class="product-description">
						                <span class="badge bg-maroon bg-flat"> 
						                	{{$user_referrer_details->total_referrals}}
						                </span>
						            </span>
						        </div>
						    </li>

						    <li class="item col-xs-3" style="border-bottom: 0px">
						        
						        <div class="product-info" style="margin-left: 0">
						            <a href="javascript:void(0)" class="product-title">

						            	{{tr('total_referrals_earnings')}}

						            </a>
						            <span class="product-description">
						                <span class="badge bg-navy bg-flat"> 
						                	{{Setting::get('currency')}} {{$user_referrer_details->total_referrals_earnings}}
						                </span>
						            </span>
						        </div>
						    </li>

						    
						</ul>

					</div>


					<div class="col-md-6">

						@if(count($subscription_payments) > 0)

							<h3 class="text-uppercase">{{tr('subscriptions')}}</h3>

							<hr>

			              	<table id="example1" class="table table-bordered table-striped">

								<thead>
								    <tr>
								      	<th>{{tr('id')}}</th>
								      	<th>{{tr('subscription')}}</th>
								      	<!-- <th>{{tr('payment_id')}}</th> -->
								      	<th>{{tr('amount')}}</th>
								      	<th>{{tr('referral_commission')}}</th>
								      	
								    </tr>
								</thead>

								<tbody>

									@foreach($subscription_payments as $i => $payment)

									    <tr>
									      	<td>{{$i+1}}</td>
									      	<td>{{$payment->title}}</td>
									      	<!-- <td>{{$payment->payment_id}}</td> -->
									      	<td>{{Setting::get('currency')}} {{$payment->amount ?: 0.00}}</td>
									      	<td>{{Setting::get('currency')}} {{$payment->referral_commission ?: 0.00}}</td>
									    </tr>

									@endforeach

								</tbody>
							</table>

							<div>
								
							</div>
						@else
							<h3 class="no-result">{{tr('no_subscription_found')}}</h3>
						@endif

					</div>

					<div class="col-md-6">

						<h3 class="text-uppercase">{{tr('pay_per_view')}}</h3>

						<hr>

						@if(count($ppv_payments) > 0)

			              	<table id="example1" class="table table-bordered table-striped">

								<thead>
								    <tr>

										<th>{{tr('id')}}</th>
										<th>{{tr('video')}}</th>
										<th>{{tr('amount')}}</th>
								      	<th>{{tr('referral_commission')}}</th>
								    </tr>
								</thead>

								<tbody>

									@foreach($ppv_payments as $i => $payment)

									    <tr>
									      	<td>{{$i+1}}</td>

									      	<td>

								      			<a href="{{route('admin.videos.view' , array('id' => $payment->video_id))}}">
								      				{{$payment->title ?: "-"}}
								      			</a>

									      	</td>

									      	<td>{{Setting::get('currency')}} {{$payment->amount ?: 0.00}}</td>

									      	<td>{{Setting::get('currency')}} {{$payment->referral_commission ?: 0.00}}</td>


									    </tr>	


										

									@endforeach
								</tbody>
							
							</table>

						@else

							<h3 class="no-result">{{tr('no_result_found')}}</h3>

						@endif

					</div>

	            </div>

          	</div>
        </div>
    </div>

@endsection