app/Http/routes.php
<?php  

use Illuminate\Support\Facades\Redis;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/clear-cache', function() {

    $exitCode = Artisan::call('config:cache');

    return back();

})->name('clear-cache');


// Generral configuration routes 

Route::post('project/configurations' , 'ApplicationController@configuration_site');

// UI

Route::get('/video_notification' , 'SampleController@video_notification');

Route::get('/upload_videoUI' , 'SampleController@upload_video');

// Unused Sample Routes

Route::post('angelo/in-app-purchase' , 'SampleController@angelo_in_app_purchase');

Route::get('/addIndex', 'ApplicationController@addIndex')->name('addIndex');

Route::get('/addAll', 'ApplicationController@addAllVideoToEs')->name('addAll');

Route::post('select/sub_category' , 'ApplicationController@select_sub_category')->name('select.sub_category');

Route::post('select/genre' , 'ApplicationController@select_genre')->name('select.genre');


// Chat Message save


Route::get('message/save' , 'ApplicationController@message_save')->name('message.save');


// Cron jobs

Route::get('/automatic/renewal', 'ApplicationController@automatic_renewal')->name('automatic.renewal');

// Application Routes

Route::get('/generate/index' , 'ApplicationController@generate_index');

Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

Route::get('/email/verification' , 'ApplicationController@email_verify')->name('email.verify');

// Installation

Route::get('/install/configure', 'InstallationController@install')->name('installTheme');

Route::get('/system/check', 'InstallationController@system_check_process')->name('system-check');

Route::post('/install/theme', 'InstallationController@theme_check_process')->name('install.theme');

Route::post('/install/settings', 'InstallationController@settings_process')->name('install.settings');

Route::get('/user_session_language/{lang}', 'ApplicationController@set_session_language')->name('user_session_language');

Route::get('admin-control', 'ApplicationController@admin_control')->name('control');

Route::post('admin-control', 'ApplicationController@save_admin_control')->name('admin.save.control');

Route::get('/user/searchall' , 'ApplicationController@search_video')->name('search');

Route::any('/user/search' , 'ApplicationController@search_all')->name('search-all');


// Social Login

Route::post('/social', array('as' => 'SocialLogin' , 'uses' => 'SocialAuthController@redirect'));

Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    

// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');


Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');


Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function(){

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    // Admin Dashboard 
    
    Route::get('/', 'AdminController@dashboard')->name('dashboard');


    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // User CRUD Operations

    Route::get('/users/list', 'AdminController@users_list')->name('users');

    Route::get('/users/create', 'AdminController@users_create')->name('users.create');
    Route::get('/users/password/{id}', 'AdminController@user_password')->name('users.password');
    

    Route::get('/users/edit', 'AdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'AdminController@users_save')->name('users.save');
    Route::post('/users/password', 'AdminController@users_password')->name('users.password');
    

    Route::get('/users/view/{id}', 'AdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'AdminController@users_delete')->name('users.delete');

    Route::get('/users/status','AdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/{id?}', 'AdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/{id}', 'AdminController@users_channels')->name('users.channels');

    Route::get('/users/history/{id}', 'AdminController@users_history')->name('users.history');
    Route::get('users/type/{id}','AdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/{id}', 'AdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/{id}', 'AdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/{id}', 'AdminController@users_wishlist_delete')->name('users.wishlist.delete');

    //User Subscriptions

    Route::get('/users/subscriptions/{id}', 'AdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save/{s_id}/u_id/{u_id}', 'AdminController@users_subscription_paln_save')->name('users.subscription.save');

    // Referrals

    Route::get('/users/referrals', 'AdminController@users_referrals')->name('users.referrals');

    Route::get('/users/referrals/view', 'AdminController@users_referrals_view')->name('users.referrals.view');


    // Channel CRUD Operations

    Route::get('/channels', 'AdminController@channels')->name('channels');

    Route::get('/channels/create', 'AdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit/{id}', 'AdminController@channels_edit')->name('channels.edit');

    Route::get('/channels/videos/{id?}', 'AdminController@channels_videos')->name('channels.videos');

    Route::post('/channels/save', 'AdminController@channels_save')->name('channels.save');

    Route::get('/channels/delete', 'AdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view/{id}', 'AdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'AdminController@channels_status_change')->name('channel.approve');

    Route::get('/channels/subscribers', 'AdminController@channels_subscribers')->name('channels.subscribers');


    // Videos CRUD Operations

    Route::get('/videos/create', 'AdminController@videos_create')->name('videos.create');

    Route::get('/videos/edit/{id}', 'AdminController@videos_edit')->name('videos.edit');

    Route::post('/videos/save', 'AdminController@videos_save')->name('videos.save');

    Route::get('/videos/images/{id}', 'AdminController@videos_images')->name('videos.images');

    Route::post('/videos/upload/image', 'AdminController@videos_upload_image')->name('videos.upload_image');

    Route::post('videos/save/default_img', 'AdminController@videos_save_default_img')->name('videos.save.default_img');

    Route::get('/videos/list/{id?}', 'AdminController@videos_list')->name('videos.list');

    Route::get('/videos/view', 'AdminController@videos_view')->name('videos.view');

    Route::post('/videos/set-ppv/{id}', 'AdminController@videos_set_ppv')->name('videos.set-ppv');

    Route::get('/videos/delete/{id}', 'AdminController@videos_delete')->name('videos.delete');

    Route::get('/videos/status/{id}', 'AdminController@videos_status')->name('videos.status');

    Route::get('/videos/publish/{id}', 'AdminController@videos_publish')->name('videos.publish');

    Route::get('/videos/remove-ppv/{id}', 'AdminController@videos_remove_ppv')->name('videos.remove-ppv');

    Route::get('/videos/wishlist/{id}', 'AdminController@videos_wishlist')->name('videos.wishlist');

    // Video compression status

    Route::get('/videos/compression/complete','AdminController@videos_compression_complete')->name('compress.status');


    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //

    public function getVideos() {

         return $this->hasMany('App\VideoTape', 'category_id', 'id');

    }


  
}

resources/views/admin/categories/channels.blade.php
@extends('layouts.admin')

@section('title', tr('channels'))

@section('content-header')

"{{$category->name}}" {{tr('category')}} {{tr('channels')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.list')}}"><i class="fa fa-list"></i> {{tr('category')}} </a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{tr('channels')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
          	<div class="box-header label-primary">
                <b style="font-size:18px;">"{{$category->name}}" {{tr('category')}} {{tr('channels')}}</b>

                <a href="{{route('admin.channels.create')}}" class="btn btn-default pull-right">{{tr('add_channel')}}</a>
            </div>
            <div class="box-body">

            	@if(count($channels) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>
						    <tr>
						      <th>{{tr('id')}}</th>
						      <th>{{tr('channel')}}</th>
						      <th>{{tr('user_name')}}</th>
						      <th>{{tr('no_of_videos')}}</th>
						      <th>{{tr('subscribers')}}</th>
						      <th>{{tr('amount')}}</th>
						      <th>{{tr('status')}}</th>
						      <th>{{tr('action')}}</th>
						    </tr>
						</thead>

						<tbody>
							@foreach($channels as $i => $channel)

							    <tr>
							      	<td>{{$i+1}}</td>
							      	<td><a target="_blank" href="{{route('admin.channels.view', $channel->id)}}">{{$channel->name}}</a></td>
							      	<td><a target="_blank" href="{{route('admin.users.view', $channel->user_id)}}">{{$channel->getUser ? $channel->getUser->name : ''}}</a></td>
							      	<td><a target="_blank" href="{{route('admin.channels.videos', array('id'=> $channel->id))}}">{{$channel->get_video_tape_count}}</a></td>
	                            	<td><a target="_blank" href="{{route('admin.channels.subscribers', array('id'=> $channel->id))}}">{{$channel->get_channel_subscribers_count}}</a></td>

	                            	<td>{{Setting::get('currency')}} {{getAmountBasedChannel($channel->id)}}</td>

								    <td>
								      		@if($channel->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								    </td>
							     	<td>
            							<ul class="admin-action btn btn-default">
            								
            								<li class="dropup">
            								
								                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
								                  {{tr('action')}} <span class="caret"></span>
								                </a>
								                <ul class="dropdown-menu">
								                  	<li role="presentation">
                                                        @if(Setting::get('admin_delete_control'))
                                                            <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                        @else
                                                            <a role="menuitem" tabindex="-1" href="{{route('admin.channels.edit' , array('id' => $channel->id))}}">{{tr('edit')}}</a>
                                                        @endif
                                                    </li>

													
                                                    
													<li class="divider" role="presentation"></li>

								                  	<li role="presentation">

									                  	@if(Setting::get('admin_delete_control'))

										                  	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

										                @else

								                  			<a role="menuitem" tabindex="-1" onclick="return confirm('Are you sure?')" href="{{route('admin.channels.delete' , array('channel_id' => $channel->id))}}">{{tr('delete')}}</a>
								                  		@endif
								                  	</li>

													<li class="divider" role="presentation"></li>

								                  	@if($channel->is_approved)
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' =>0))}}">{{tr('decline')}}</a></li>
								                  	@else
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' => 1))}}">{{tr('approve')}}</a></li>
								                  	@endif

								                </ul>
              								</li>
            							</ul>
							      </td>
							    </tr>
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_result_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', tr('create_category'))

@section('content-header', tr('create_category'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.list')}}"><i class="fa fa-key"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('create_category')}}</li>
@endsection

@section('content')

@include('notification.notify')

@include('admin.categories._form')

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_category'))

@section('content-header', tr('edit_category'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.list')}}"><i class="fa fa-key"></i> {{tr('categories')}}</a></li>
    <li class="active">{{tr('edit_category')}}</li>
@endsection

@section('content')

@include('notification.notify')

@include('admin.categories._form')

@endsection

resources/views/admin/categories/videos.blade.php
@extends('layouts.admin')

@section('title', tr('videos'))

@section('content-header')

"{{$category->name}}" {{tr('category')}} {{tr('videos')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.categories.list')}}"><i class="fa fa-list"></i> {{tr('category')}} </a></li>
    <li class="active"><i class="fa fa-video-camera"></i> {{tr('videos')}}</li>
@endsection

@section('content')

    @include('notification.notify')
	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">

          	<div class="box-header label-primary">
                <b style="font-size:18px;">"{{$category->name}}" {{tr('category')}} {{tr('videos')}}</b>
                <a href="{{route('admin.videos.create')}}" class="btn btn-default pull-right">{{tr('add_video')}}</a>
            </div>

            <div class="box-body">

            	@if(count($videos) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>

						    <tr>
								<th>{{tr('id')}}</th>
								<th>{{tr('channel')}}</th>
								<th>{{tr('title')}}</th>

								<?php /*@if(Setting::get('is_banner_video'))
									<th>{{tr('slider_video')}}</th>
								@endif */?>

								<!-- <th>{{tr('likes')}}</th>
								<th>{{tr('dislikes')}}</th> -->
								<th>{{tr('amount')}}</th>

								@if(Setting::get('is_payper_view'))
									<th>{{tr('ppv')}}</th>
								@endif
								<th>{{tr('is_ads')}}</th>

								<th>{{tr('status')}}</th>
								<th>{{tr('action')}}</th>
						    </tr>
						    
						</thead>

						<tbody>

							@foreach($videos as $i => $video)

							    <tr>
							      	
							      	<td><a href="{{route('admin.videos.view' , array('id' => $video->video_tape_id))}}">{{$i+1}}</a></td>
							      	
							      	<td><a href="{{route('admin.channels.view', $video->channel_id)}}">{{$video->channel_name}}</a></td>
							      	
							      	<td><a href="{{route('admin.videos.view' , array('id' => $video->video_tape_id))}}"> {{substr($video->title , 0,25)}}...</a></td>
							      	
							      	<?php /*@if(Setting::get('theme') == 'default')
							      	
								      	<td>
								      		@if($video->is_home_slider == 0 && $video->is_approved && $video->status)
								      			<a href="{{route('admin.slider.video' , $video['video_tape_id'])}}"><span class="label label-danger">{{tr('set_slider')}}</span></a>
								      		@elseif($video['is_home_slider'])
								      			<span class="label label-success">{{tr('slider')}}</span>
								      		@else
								      			-
								      		@endif
								      	</td>

							      	@endif */?>

							      	<td><b>{{Setting::get('currency')}} {{$video->admin_ppv_amount}}</b></td>

							      	@if(Setting::get('is_payper_view'))
							      	<td class="text-center">
							      		@if($video->ppv_amount > 0)
							      			<span class="label label-success">{{tr('yes')}}</span>
							      		@else
							      			<span class="label label-danger">{{tr('no')}}</span>
							      		@endif
							      	</td>
							      	@endif

							      	<td class="text-center">
							      		
							      		@if($video->ad_status)
							      			<span class="label label-success">{{tr('yes')}}</span>
							      		@else
							      			<span class="label label-danger">{{tr('no')}}</span>
							      		@endif

							      	</td>

							      	<td>
							      		@if ($video->compress_status == 0)
							      			<span class="label label-danger">{{tr('compress')}}</span>
							      		@else
								      		@if($video->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								       	@endif
							      	</td>
								    <td>
            							<ul class="admin-action btn btn-default">
            								<li class="dropup">
								                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
								                  {{tr('action')}} <span class="caret"></span>
								                </a>
								                <ul class="dropdown-menu">
								                	@if ($video->compress_status == 1)
								                  	<li role="presentation">
                                                        @if(Setting::get('admin_delete_control'))
                                                            <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                        @else
                                                            <a role="menuitem" tabindex="-1" href="{{route('admin.videos.edit' , array('id' => $video->video_tape_id))}}">{{tr('edit')}}</a>
                                                        @endif
                                                    </li>
                                                    @endif
								                  	<li role="presentation"><a role="menuitem" tabindex="-1" target="_blank" href="{{route('admin.videos.view' , array('id' => $video->video_tape_id))}}">{{tr('view')}}</a></li>

								               		@if(Setting::get('is_payper_view'))

								                  		<li role="presentation">
								                  			<a role="menuitem" tabindex="-1" data-toggle="modal" data-target="#{{$video->video_tape_id}}">{{tr('pay_per_view')}}</a>
								                  		</li>

								                  	@endif

								                  	<li class="divider" role="presentation"></li>

								                  	@if($video->is_approved)
								                		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.videos.status',$video->video_tape_id)}}">{{tr('decline')}}</a></li>
								                	@else
								                		@if ($video->compress_status == 0)
								                			<li role="presentation"><a role="menuitem" tabindex="-1">{{tr('compress')}}</a></li>
								                		@else 
								                  			<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.videos.status',$video->video_tape_id)}}">{{tr('approve')}}</a></li>
								                  		@endif
								                  	@endif

								                  	@if($video->publish_status == 0 && $video->compress_status == 1)
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.videos.publish',$video->video_tape_id)}}">{{tr('publish')}}</a></li>
								                  	@endif

								                  	@if ($video->compress_status == 1)
									                  	<li role="presentation">
									                  		@if(Setting::get('admin_delete_control'))

										                  	 	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

										                  	@else
									                  			<a role="menuitem" tabindex="-1" onclick="return confirm('Are you sure?')" href="{{route('admin.videos.delete' , array('id' => $video->video_tape_id))}}">{{tr('delete')}}</a>
									                  		@endif
									                  	</li>
								                  	@endif

								                  	<li class="divider" role="presentation"></li>

								                  	@if($video->ad_status && !$video->getScopeVideoAds) 

								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video_ads.create', array('video_tape_id'=>$video->video_tape_id))}}">{{tr('video_ad')}}</a></li>

								                  	@else

								                  		@if ($video->getScopeVideoAds)

								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.video-ads.view' , array('id' => $video->getScopeVideoAds->id))}}">{{tr('view_ad')}}</a></li>

								                  		@endif

								                  	@endif

								                  	<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.ads-details.ad-status-change',$video->video_tape_id)}}">{{ ($video->ad_status) ? tr('disable_ad') : tr('enable_ad')}}</a></li>

								                </ul>
              								</li>
            							</ul>
								    </td>
							    </tr>

							    <div id="{{$video->video_tape_id}}" class="modal fade" role="dialog">
								  <div class="modal-dialog">
								  <form action="{{route('admin.videos.set-ppv', $video->video_tape_id)}}" method="POST">
									    <!-- Modal content-->
									   	<div class="modal-content">
									      <div class="modal-header">
									        <button type="button" class="close" data-dismiss="modal">&times;</button>
									        <h4 class="modal-title">{{tr('pay_per_view')}}</h4>
									      </div>
									      <div class="modal-body">
									        <div class="row">

									        	<input type="hidden" name="ppv_created_by" id="ppv_created_by" value="{{Auth::guard('admin')->user()->id}}">
									        	<div class="col-lg-3">
									        		<label>{{tr('type_of_user')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                  <div class="input-group">
								                        <input type="radio" name="type_of_user" value="{{NORMAL_USER}}" {{($video->type_of_user == 0 || $video->type_of_user == '') ? 'checked' : (($video->type_of_user == NORMAL_USER) ? 'checked' : '')}}>&nbsp;<label>{{tr('normal_user')}}</label>&nbsp;
								                        <input type="radio" name="type_of_user" value="{{PAID_USER}}" {{($video->type_of_user == PAID_USER) ? 'checked' : ''}}>&nbsp;<label>{{tr('paid_user')}}</label>&nbsp;
								                        <input type="radio" name="type_of_user" value="{{BOTH_USERS}}" {{($video->type_of_user == BOTH_USERS) ? 'checked' : ''}}>&nbsp;<label>{{tr('both_user')}}</label>
								                  </div>
								                  <!-- /input-group -->
								                </div>
								            </div>
								            <br>
								            <div class="row">
									        	<div class="col-lg-3">
									        		<label>{{tr('type_of_subscription')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                  <div class="input-group">
								                        <input type="radio" name="type_of_subscription" value="{{ONE_TIME_PAYMENT}}"  {{($video->type_of_subscription == 0 || $video->type_of_subscription == '') ? 'checked' : (($video->type_of_subscription == ONE_TIME_PAYMENT) ? 'checked' : '')}}>&nbsp;<label>{{tr('one_time_payment')}}</label>&nbsp;
								                        <input type="radio" name="type_of_subscription" value="{{RECURRING_PAYMENT}}" {{($video->type_of_subscription == RECURRING_PAYMENT) ? 'checked' : ''}}>&nbsp;<label>{{tr('recurring_payment')}}</label>
								                  </div>
								                  <!-- /input-group -->
								                </div>
								            </div>
								            <br>
								            <div class="row">
									        	<div class="col-lg-3">
									        		<label>{{tr('amount')}}</label>
									        	</div>
								                <div class="col-lg-9">
								                       <input type="number" required value="{{$video->ppv_amount}}" name="ppv_amount" class="form-control" id="amount" placeholder="{{tr('amount')}}" step="any" maxlength="6">
								                  <!-- /input-group -->
								                </div>
								            </div>
									      </div>
									      <div class="modal-footer">
									      	<div class="pull-left">
									      		@if($video->ppv_amount > 0)
									       			<a class="btn btn-danger" href="{{route('admin.videos.remove-ppv', $video->video_tape_id)}}">{{tr('remove_pay_per_view')}}</a>
									       		@endif
									       	</div>
									        <div class="pull-right">
										        <button type="button" class="btn btn-default" data-dismiss="modal">{{tr('cancel')}}</button>
										        <button type="submit" class="btn btn-primary">{{tr('submit')}}</button>
										    </div>
										    <div class="clearfix"></div>
									      </div>
									    </div>
									</form>
								  </div>
								</div>
								<!-- Modal -->
								
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_video_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection