app/Http/routes.php
Route::get('/callback/{provider}', 'SocialAuthController@callback');

// Referral link generate

Route::get('/rc/{referral_code}', 'UserController@referrals_signup')->name('referrals_signup');

// Embed Links

Route::get('/embed', 'ApplicationController@embed_video')->name('embed_video');

// Admin to users login

Route::get('/master/login', 'UserController@master_login')->name('master.login');

// CRON

Route::get('/publish/video', 'ApplicationController@cron_publish_video')->name('publish');

Route::get('/notification/payment', 'ApplicationController@send_notification_user_payment')->name('notification.user.payment');

Route::get('/payment/expiry', 'ApplicationController@user_payment_expiry')->name('user.payment.expiry');

Route::get('cron_delete_video', 'ApplicationController@cron_delete_video');
    

// Static Pages

Route::get('/privacy', 'UserApiController@privacy')->name('user.privacy');

Route::get('/help', 'UserApiController@help')->name('user.help');

Route::get('/terms_condition', 'UserApiController@terms')->name('user.terms');


Route::get('/about', 'ApplicationController@about')->name('user.about');

Route::get('/privacy_policy', 'ApplicationController@privacy')->name('user.privacy_policy');

Route::get('/terms', 'ApplicationController@terms')->name('user.terms-condition');

Route::get('page_view/{id}', 'UserController@page_view')->name('page_view');


Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function(){

    Route::get('login', 'Auth\AdminAuthController@showLoginForm')->name('login');

    Route::post('login', 'Auth\AdminAuthController@login')->name('login.post');

    Route::get('logout', 'Auth\AdminAuthController@logout')->name('logout');

    Route::get('secure', 'AdminController@secure')->name('secure');

    // Registration Routes...

    Route::get('register', 'Auth\AdminAuthController@showRegistrationForm');

    Route::post('register', 'Auth\AdminAuthController@register');

    // Password Reset Routes...
    Route::get('password/reset/{token?}', 'Auth\AdminPasswordController@showResetForm');

    Route::post('password/email', 'Auth\AdminPasswordController@sendResetLinkEmail');

    Route::post('password/reset', 'Auth\AdminPasswordController@reset');

    // Admin Dashboard 
    
    Route::get('/', 'AdminController@dashboard')->name('dashboard');


    Route::get('/payment/failure' , 'ApplicationController@payment_failure')->name('payment.failure');

    // User CRUD Operations

    Route::get('/users/list', 'AdminController@users_list')->name('users');

    Route::get('/users/create', 'AdminController@users_create')->name('users.create');
    Route::get('/users/password/{id}', 'AdminController@user_password')->name('users.password');
    

    Route::get('/users/edit', 'AdminController@users_edit')->name('users.edit');
    
    Route::post('/users/save', 'AdminController@users_save')->name('users.save');
    Route::post('/users/password', 'AdminController@users_password')->name('users.password');
    

    Route::get('/users/view/{id}', 'AdminController@users_view')->name('users.view');

    Route::get('/users/delete', 'AdminController@users_delete')->name('users.delete');

    Route::get('/users/status','AdminController@users_status_change')->name('users.status');

    Route::get('/users/verify/{id?}', 'AdminController@users_verify_status')->name('users.verify');

    Route::get('/users/channels/{id}', 'AdminController@users_channels')->name('users.channels');

    Route::get('/users/history/{id}', 'AdminController@users_history')->name('users.history');
    Route::get('users/type/{id}','AdminController@users_type_list')->name('users.type');

    Route::get('/users/history/delete/{id}', 'AdminController@users_history_delete')->name('users.history.delete');

    Route::get('/users/wishlist/{id}', 'AdminController@users_wishlist')->name('users.wishlist');

    Route::get('/users/wishlist/delete/{id}', 'AdminController@users_wishlist_delete')->name('users.wishlist.delete');

    //User Subscriptions

    Route::get('/users/subscriptions/{id}', 'AdminController@users_subscriptions')->name('users.subscriptions.plans');

    Route::get('/users/subscriptions/save/{s_id}/u_id/{u_id}', 'AdminController@users_subscription_paln_save')->name('users.subscription.save');

    // Referrals

    Route::get('/users/referrals', 'AdminController@users_referrals')->name('users.referrals');

    Route::get('/users/referrals/view', 'AdminController@users_referrals_view')->name('users.referrals.view');


    // Channel CRUD Operations

    Route::get('/channels', 'AdminController@channels')->name('channels');

    Route::get('/channels/create', 'AdminController@channels_create')->name('channels.create');

    Route::get('/channels/edit/{id}', 'AdminController@channels_edit')->name('channels.edit');

    Route::get('/channels/videos/{id?}', 'AdminController@channels_videos')->name('channels.videos');

    Route::post('/channels/save', 'AdminController@channels_save')->name('channels.save');

    Route::get('/channels/delete', 'AdminController@channels_delete')->name('channels.delete');

    Route::get('/channels/view/{id}', 'AdminController@channels_view')->name('channels.view');

    Route::get('/channels/status/change', 'AdminController@channels_status_change')->name('channel.approve');

    Route::get('/channels/subscribers', 'AdminController@channels_subscribers')->name('channels.subscribers');


    // Videos CRUD Operations

    Route::get('/videos/create', 'AdminController@videos_create')->name('videos.create');

    Route::get('/videos/edit/{id}', 'AdminController@videos_edit')->name('videos.edit');

    Route::post('/videos/save', 'AdminController@videos_save')->name('videos.save');

    Route::get('/videos/images/{id}', 'AdminController@videos_images')->name('videos.images');

    Route::post('/videos/upload/image', 'AdminController@videos_upload_image')->name('videos.upload_image');

    Route::post('videos/save/default_img', 'AdminController@videos_save_default_img')->name('videos.save.default_img');

    Route::get('/videos/list/{id?}', 'AdminController@videos_list')->name('videos.list');

    Route::get('/videos/view', 'AdminController@videos_view')->name('videos.view');

    Route::post('/videos/set-ppv/{id}', 'AdminController@videos_set_ppv')->name('videos.set-ppv');

    Route::get('/videos/delete/{id}', 'AdminController@videos_delete')->name('videos.delete');

    Route::get('/videos/status/{id}', 'AdminController@videos_status')->name('videos.status');

    Route::get('/videos/publish/{id}', 'AdminController@videos_publish')->name('videos.publish');

    Route::get('/videos/remove-ppv/{id}', 'AdminController@videos_remove_ppv')->name('videos.remove-ppv');

    Route::get('/videos/wishlist/{id}', 'AdminController@videos_wishlist')->name('videos.wishlist');

    // Video compression status

    Route::get('/videos/compression/complete','AdminController@videos_compression_complete')->name('compress.status');


    // Videos

    Route::get('/live_videos', 'AdminController@live_videos')->name('live-videos.index');

    Route::get('/live-videos/list', 'AdminController@live_videos_history')->name('live-videos.history');

    Route::get('/live-videos/view/{id}', 'AdminController@live_videos_view')->name('live-videos.view');


    // Banner Videos

    Route::get('/banner/videos/set/{id}', 'AdminController@banner_videos_set')->name('banner.videos.set');

    Route::get('/banner/videos', 'AdminController@banner_videos')->name('banner.videos');

    Route::get('/banner/videos/create', 'AdminController@banner_videos_create')->name('banner.videos.create');

    Route::get('/banner/videos/remove/{id}', 'AdminController@banner_videos_remove')->name('banner.videos.remove');


    // Spam Videos

    Route::get('/spam-videos', 'AdminController@spam_videos')->name('spam-videos');

    Route::get('/spam-videos/user-reports/{id}', 'AdminController@spam_videos_user_reports')->name('spam-videos.user-reports');

    Route::get('/spam/per-user-reports/{id}', 'AdminController@spam_videos_each_user_reports')->name('spam-videos.per-user-reports');

    Route::get('/unspam-video/{id}', 'AdminController@spam_videos_unspam')->name('spam-videos.unspam-video');


    // Reviews

    Route::get('/reviews', 'AdminController@user_reviews')->name('reviews');

    Route::get('/reviews/delete', 'AdminController@user_reviews_delete')->name('reviews.delete');


    // Ads

    Route::get('ads-details/create','AdminController@ads_details_create')->name('ads-details.create');

    Route::get('ads-details/edit','AdminController@ads_details_edit')->name('ads-details.edit');

    Route::post('ads-details/save','AdminController@ads_details_save')->name('ads-details.save');

    Route::get('ads-details/index','AdminController@ads_details_index')->name('ads-details.index');

    Route::get('ads-details/view','AdminController@ads_details_view')->name('ads-details.view');

    Route::get('ads-details/status','AdminController@ads_details_status')->name('ads-details.status');

    Route::get('ads-details/delete','AdminController@ads_details_delete')->name('ads-details.delete');

    Route::get('ads-details/ad-status/{id?}', 'AdminController@ads_details_ad_status_change')->name('ads-details.ad-status-change');

    // Assign Ads

    Route::post('video-ads/assign/ads', 'AdminController@video_ads_assign_ad')->name('video-ads.assign.ads');

    Route::get('videos/assign-ad', 'AdminController@video_assign_ad')->name('videos.assign_ad');

    Route::get('videos/sponsored-status/{id}', 'AdminController@sponsored_status_change')->name('videos.sponsored-status-change');

    // Exports tables

    Route::get('/users/export/', 'AdminExportController@users_export')->name('users.export');

    Route::get('/channels/export/', 'AdminExportController@channels_export')->name('channels.export');

    Route::get('/videos/export/', 'AdminExportController@videos_export')->name('videos.export');

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Helpers\Helper;

class Channel extends Model
{
    //

    public function videoTape() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse();
    }

    /**
     * Get the video record associated with the flag.
     */
    public function getUser()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
    /**
     * Save the unique ID 
     *
     *
     */
    public function setUniqueIdAttribute($value){

        $this->attributes['unique_id'] = uniqid(str_replace(' ', '-', $value));

    }

    public function getVideos() {
        return $this->hasMany('App\VideoTape')->leftJoin('channels' , 'video_tapes.channel_id' , '=' , 'channels.id')->videoResponse()->where('status', DEFAULT_TRUE)->where('is_approved', DEFAULT_TRUE);
    }

    public function getVideoTape() {
        return $this->hasMany('App\VideoTape');
    }


    public function getChannelSubscribers() {
        return $this->hasMany('App\ChannelSubscription');
    }

    /**
     * Boot function for using with User Events
     *
     * @return void
     */

    public static function boot()
    {
        //execute the parent's boot method 
        parent::boot();

        //delete your related models here, for example
        static::deleting(function($model)
        {

            if($model->picture) {
                Helper::delete_picture($model->picture, "/uploads/channels/picture/");
            }

            if($model->cover) {
                Helper::delete_picture($model->cover, "/uploads/channels/cover/");
            }

            if (count($model->getVideoTape) > 0) {

                foreach ($model->getVideoTape as $key => $value) {

                    Helper::delete_picture($value->video, "/uploads/videos/");

                    Helper::delete_picture($value->subtitle, "/uploads/subtitles/"); 

                    if ($value->banner_image) {

                        Helper::delete_picture($value->banner_image, "/uploads/images/");
                    }

                    Helper::delete_picture($value->default_image, "/uploads/images/");

                    if ($value->video_path) {

                        $explode = explode(',', $value->video_path);

                        if (count($explode) > 0) {


                            foreach ($explode as $key => $exp) {


                                Helper::delete_picture($exp, "/uploads/videos/");

                            }

                        }
                

                    }

                   $value->delete();    

                }

            }

             if (count($model->getChannelSubscribers) > 0) {

                foreach ($model->getChannelSubscribers as $key => $value) {

                   $value->delete();    

                }

            }

        }); 

    }


}

resources/views/admin/channels/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_channel'))

@section('content-header', tr('add_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('add_channel')}}</li>
@endsection


@section('content')

@include('admin.channels._form')

@endsection

@section('styles')

<link href="{{asset('assets/iCheck/skins/minimal/pink.css')}}" rel="stylesheet">

@endsection

resources/views/admin/channels/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_channel'))

@section('content-header', tr('edit_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('edit_channel')}}</li>
@endsection

@section('content')

@include('admin.channels._form')

@endsection

@section('styles')

<link href="{{asset('assets/iCheck/skins/minimal/pink.css')}}" rel="stylesheet">

@endsection

resources/views/admin/channels/list.blade.php
@extends('layouts.admin')

@section('title', tr('channels'))

@section('content-header')

@if(isset($user)) <span class="text-green"> {{$user->name}} </span>- @endif {{tr('channels')}}

@endsection

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li class="active"><i class="fa fa-suitcase"></i> {{tr('channels')}}</li>
@endsection

@section('content')

	@include('notification.notify')

	<div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
          	<div class="box-header label-primary">
                <b style="font-size:18px;">{{tr('channels')}}</b>
                <a href="{{route('admin.channels.create')}}" class="btn btn-default pull-right">{{tr('add_channel')}}</a>

                <!-- EXPORT OPTION START -->

	          	@if(count($channels) > 0 )
	                  
	            <ul class="admin-action btn btn-default pull-right" style="margin-right: 20px">        
	            	<li class="dropdown">
	                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                      {{tr('export')}} <span class="caret"></span>
	                    </a>

	                    <ul class="dropdown-menu">
	                        <li role="presentation">
	                          <a role="menuitem" tabindex="-1" href="{{route('admin.channels.export' , ['format' => 'xls'])}}">
	                            <span class="text-red"><b>{{tr('excel_sheet')}}</b></span>
	                          </a>
	                        </li>

	                        <li role="presentation">
	                          <a role="menuitem" tabindex="-1" href="{{route('admin.channels.export' , ['format' => 'csv'])}}">
	                            <span class="text-blue"><b>{{tr('csv')}}</b></span>
	                          </a>
	                        </li>
	                    </ul>
	              	</li>
	            </ul>

	          @endif

              <!-- EXPORT OPTION END -->

            </div>
            <div class="box-body table-responsive">

            	@if(count($channels) > 0)

	              	<table id="example1" class="table table-bordered table-striped">

						<thead>
						    <tr>
						      <th>{{tr('id')}}</th>
						      <th>{{tr('channel')}}</th>
						      <th>{{tr('user_name')}}</th>
						      <th>{{tr('no_of_videos')}}</th>
						      <th>{{tr('subscribers')}}</th>
						      <th>{{tr('amount')}}</th>
						      <th>{{tr('status')}}</th>
						      <th>{{tr('action')}}</th>
						    </tr>
						</thead>

						<tbody>
							@foreach($channels as $i => $channel)
							 
							    <tr>
							      	<td>{{$i+1}}</td>
							      	<td><a target="_blank" href="{{route('admin.channels.view', $channel->id)}}">{{$channel->name}}</a>

							      		@if($channel->channel_type == CHANNEL_TYPE_PAID)

							      			<span class="text-green pull-right"><i class="fa fa-check-circle"></i></span>

							      		@endif

							      	</td>
							      	<td><a target="_blank" href="{{route('admin.users.view', $channel->user_id)}}">{{$channel->getUser ? $channel->getUser->name : ''}}</a></td>
							      	<td><a target="_blank" href="{{route('admin.channels.videos', array('id'=> $channel->id))}}">{{$channel->get_video_tape_count}}</a></td>
	                            	<td><a target="_blank" href="{{route('admin.channels.subscribers', array('id'=> $channel->id))}}">{{$channel->get_channel_subscribers_count}}</a></td>

	                            	<td>{{Setting::get('currency')}} {{getAmountBasedChannel($channel->id)}}</td>

								    <td>
								      		@if($channel->is_approved)
								      			<span class="label label-success">{{tr('approved')}}</span>
								       		@else
								       			<span class="label label-warning">{{tr('pending')}}</span>
								       		@endif
								    </td>
							     	<td>
            							<ul class="admin-action btn btn-default">
            								
            								<li class="{{$i <=2 ? 'dropdown' : 'dropup'}}">
            								
								                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
								                  {{tr('action')}} <span class="caret"></span>
								                </a>
								                <ul class="dropdown-menu">
								                  	<li role="presentation">
                                                        @if(Setting::get('admin_delete_control'))
                                                            <a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('edit')}}</a>
                                                        @else
                                                            <a role="menuitem" tabindex="-1" href="{{route('admin.channels.edit' , array('id' => $channel->id))}}">{{tr('edit')}}</a>
                                                        @endif
                                                    </li>

													
                                                    
													<li class="divider" role="presentation"></li>

								                  	<li role="presentation">

									                  	@if(Setting::get('admin_delete_control'))

										                  	<a role="button" href="javascript:;" class="btn disabled" style="text-align: left">{{tr('delete')}}</a>

										                @else

								                  			<a role="menuitem" tabindex="-1" onclick="return confirm('Are you sure?')" href="{{route('admin.channels.delete' , array('channel_id' => $channel->id))}}">{{tr('delete')}}</a>
								                  		@endif
								                  	</li>

													<li class="divider" role="presentation"></li>

													<?php 

								                  		$channel_approve_notes = tr('channel_approve_notes');

								                  		$channel_decline_notes = tr('channel_decline_notes');

								                  	?>

								                  	@if($channel->is_approved)
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' =>0))}}" onclick='return confirm("{{$channel_decline_notes}}")'>{{tr('decline')}}</a></li>
								                  	@else
								                  		<li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('admin.channel.approve' , array('id' => $channel->id , 'status' => 1))}}" onclick='return confirm("{{$channel_approve_notes}}")'>{{tr('approve')}}</a></li>
								                  	@endif

													<li class="divider" role="presentation"></li>

													<li role="presentation">
														<a role="menuitem" tabindex="-1" href="{{route('admin.user_subscriptions.index' , ['channel_id' => $channel->id])}}">{{tr('subscriptions')}}
														</a>
													</li>

								                </ul>
              								</li>
            							</ul>
							      </td>
							    </tr>
							@endforeach
						</tbody>
					</table>
				@else
					<h3 class="no-result">{{tr('no_result_found')}}</h3>
				@endif
            </div>
          </div>
        </div>
    </div>

@endsection

resources/views/admin/channels/view.blade.php
@extends('layouts.admin')

@section('title', tr('view_channel'))

@section('content-header', tr('view_channel'))

@section('breadcrumb')
    <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard"></i>{{tr('home')}}</a></li>
    <li><a href="{{route('admin.channels')}}"><i class="fa fa-suitcase"></i> {{tr('channels')}}</a></li>
    <li class="active">{{tr('view_channel')}}</li>
@endsection



@section('content')

  @include('notification.notify')

  <div class="col-md-12">
          <!-- Widget: user widget style 1 -->
          <div class="box box-widget widget-user">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header bg-black" style="background: #000 url('{{$channel->cover}}') center center;">
              <h3 class="widget-user-username text-capitalize">{{$channel->name}}</h3>
              <h5 class="widget-user-desc">{{tr('channel')}}</h5>
            </div>
            <div class="widget-user-image">
              <img class="img-circle" src="{{$channel->picture}}" alt="User Avatar" style="height: 90px">
            </div>
            <div class="box-footer">
              <div class="row">
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    <h5 class="description-header"><a target="_blank" href="{{route('admin.channels.videos', array('id'=> $channel->id))}}">{{$channel->get_video_tape_count}}</a></h5>
                    <span class="description-text">{{tr('videos')}}</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4 border-right">
                  <div class="description-block">
                    <h5 class="description-header"><a  target="_blank" href="{{route('admin.channels.subscribers', array('id'=> $channel->id))}}">{{$channel->get_channel_subscribers_count}}</a></h5>
                    <span class="description-text">{{tr('subscribers')}}</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-4">
                  <div class="description-block">
                    <h5 class="description-header">{{Setting::get('currency')}} {{number_format_short($channel_earnings)}}</h5>
                    <span class="description-text">{{tr('earnings')}}</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
          </div>
          <!-- /.widget-user -->

          <!-- Box Comment -->
          <div class="box box-widget">
            <div class="box-header with-border">
              <div class="user-block">
                <img class="img-circle" src="{{$channel->user_picture}}" alt="{{$channel->user_name}}">
                <span class="username"><a target="_blank" href="{{route('admin.users.view', $channel->user_id)}}">{{$channel->user_name}}</a></span>
                <span class="description">{{tr('shared_publicly')}} - {{$channel->created_at->diffForHumans()}}</span>
              </div>
                <div class="pull-right">
                  <a href="{{route('admin.channels.edit' ,['id'=>$channel->id])}}" class="btn btn-xs btn-warning" title="Edit">
                      <i class="fa fa-edit"></i>
                  </a>
                </div>
             
              <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">

              <div class="row col-md-12">
                <!-- Custom Tabs -->
                <div class="nav-tabs-custom">
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab">{{tr('about_channel')}}</a></li>
                    <li><a href="#tab_2" data-toggle="tab">{{tr('videos')}}</a></li>
                    <li><a href="#tab_3" data-toggle="tab">{{tr('subscribers')}}</a></li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active" id="tab_1">
                      <table class="table">
                        <tr>
                          <th>{{tr('name')}}</th>
                          <td>{{$channel->name}}</td>
                        </tr>
                        <tr>
                          <th>{{tr('description')}}</th>
                          <td><?= $channel->description?></td>
                        </tr>
                      </table>

                     
                    </div>
                    <!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_2">

                      <blockquote>
                        <p>{{tr('videos_short_notes')}}</p>
                        <small>{{tr('to_view_more')}} <cite><a target="_blank" href="{{route('admin.channels.videos', array('id'=> $channel->id))}}">{{tr('click_here')}}</a></cite></small>
                    </blockquote>

                    @if($channel->get_video_tape_count > 0)

                      @foreach($videos as $video)
                      <div class="box-comments">
                        <!-- /.box-comment -->
                        <div class="box-comment">
                          <!-- User image -->
                          <img class="img-circle img-sm" src="{{$video->default_image}}" alt="{{$channel->user_name}}">

                          <div class="comment-text">
                                <span class="username">
                                  <a href="{{route('admin.videos.view', array('id' => $video->id))}}" target="_blank">{{$video->title}}</a>
                                  <span class="text-muted pull-right">{{$video->created_at->diffForHumans()}}</span>
                                </span><!-- /.username -->
                              <div class="description"><?=$video->description?></div>
                          </div>
                          <!-- /.comment-text -->
                        </div>
                      </div>
                      @endforeach

                    @else


                        {{tr('no_videos_found')}}

                    @endif
                    </div>
                    <!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_3">
                      <blockquote>
                          <p>{{tr('subscribers_short_notes')}}</p>
                          <small>{{tr('to_view_more')}} <cite><a  target="_blank" href="{{route('admin.channels.subscribers', array('id'=> $channel->id))}}">{{tr('click_here')}}</a></cite></small>
                      </blockquote>

                      @if($channel->get_channel_subscribers_count > 0)

                        @foreach($subscribers as $i => $subscriber)

                          <div class="col-sm-6 col-md-6">
                            <div class="box box-solid">
                                <div class="box-body">
                                    <h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                                        {{$subscriber->user_name}}
                                    </h4>
                                    <div class="media">
                                        <div class="media-left">
                                             <a href="{{route('admin.users.view', array('id' => $subscriber->user_id))}}" target="_blank">
                                                <img src="{{$subscriber->user_picture}}" alt="{{$subscriber->user_name}}" class="media-object" style="width: 150px;height: auto;border-radius: 4px;box-shadow: 0 1px 3px rgba(0,0,0,.15);">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <div class="clearfix">
                                                <p class="pull-right">
                                                     <a class="btn btn-success btn-sm" href="{{route('admin.users.view', array('id' => $subscriber->user_id))}}" target="_blank">
                                                        {{tr('view')}}
                                                    </a>
                                                </p>

                                                <h4 style="margin-top: 0;text-align:nowrap;overflow: hidden;text-overflow: ellipsis;">{{$subscriber->email}}</h4>

                                                <p style="max-height: 80px;overflow-y: hidden;">{{$subscriber->description}}</p>
                                                <!-- <p style="margin-bottom: 0">
                                                    <i class="fa fa-shopping-cart margin-r5"></i> 12+ purchases
                                                </p> -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          </div>

                          @if ($i % 2 == 0)  @else 

                          <div class="clearfix"></div>

                          @endif

                        @endforeach

                      @else


                          {{tr('no_subscribers_found')}}

                      @endif

                      <div class="clearfix"></div>
                    </div>
                    <!-- /.tab-pane -->
                  </div>
                  <!-- /.tab-content -->
                </div>
                <!-- nav-tabs-custom -->
              </div>

             <div class="clearfix"></div>
             
            </div>
          
          </div>

          <div class="clearfix"></div>
        
  </div>

  <div class="clearfix"></div>
@endsection